# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1353, 883)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_3.addWidget(self.pushButton_10, 2, 3, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_3.addWidget(self.pushButton_12, 2, 5, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_3.addWidget(self.pushButton_11, 2, 4, 1, 1)
        self.table = QtGui.QTableWidget(self.centralwidget)
        self.table.setAutoFillBackground(False)
        self.table.setMidLineWidth(0)
        self.table.setAlternatingRowColors(True)
        self.table.setRowCount(12)
        self.table.setColumnCount(37)
        self.table.setObjectName(_fromUtf8("table"))
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(11, item)
        self.table.horizontalHeader().setDefaultSectionSize(35)
        self.table.verticalHeader().setDefaultSectionSize(52)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.table, 1, 0, 1, 6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.table_vehicles = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_vehicles.sizePolicy().hasHeightForWidth())
        self.table_vehicles.setSizePolicy(sizePolicy)
        self.table_vehicles.setMaximumSize(QtCore.QSize(16777215, 113))
        self.table_vehicles.setRowCount(3)
        self.table_vehicles.setColumnCount(4)
        self.table_vehicles.setObjectName(_fromUtf8("table_vehicles"))
        self.verticalLayout_7.addWidget(self.table_vehicles)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.table_drivers = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_drivers.sizePolicy().hasHeightForWidth())
        self.table_drivers.setSizePolicy(sizePolicy)
        self.table_drivers.setMaximumSize(QtCore.QSize(16777215, 113))
        self.table_drivers.setRowCount(3)
        self.table_drivers.setColumnCount(4)
        self.table_drivers.setObjectName(_fromUtf8("table_drivers"))
        self.verticalLayout_8.addWidget(self.table_drivers)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 0, 1, 6)
        self.pushButton_9 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_3.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 2, 1, 2)
        self.pushButton_14 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_3.addWidget(self.pushButton_14, 0, 4, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout_3.addWidget(self.pushButton_13, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1353, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_2.setText(_translate("MainWindow", "Service", None))
        self.pushButton.setText(_translate("MainWindow", "MOT", None))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton", None))
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Jan", None))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Feb", None))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mar", None))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Apr", None))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "May", None))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Jun", None))
        item = self.table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Jul", None))
        item = self.table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Aug", None))
        item = self.table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Sep", None))
        item = self.table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Oct", None))
        item = self.table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Nov", None))
        item = self.table.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Dec", None))
        self.pushButton_3.setText(_translate("MainWindow", "Add", None))
        self.pushButton_5.setText(_translate("MainWindow", "Edit", None))
        self.pushButton_4.setText(_translate("MainWindow", "Delete", None))
        self.label_2.setText(_translate("MainWindow", "Vehicles", None))
        self.pushButton_8.setText(_translate("MainWindow", "Add", None))
        self.pushButton_7.setText(_translate("MainWindow", "Edit", None))
        self.pushButton_6.setText(_translate("MainWindow", "Delete", None))
        self.label_3.setText(_translate("MainWindow", "Drivers", None))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton", None))
        self.label.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton", None))

